[package]
name = "networking"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
identity = { path = "../identity" }
messaging = { path = "../messaging" }
device_settings = { path = "../device_settings" }
crypto = { path = "../commons/crypto" }
settings = { path = "../commons/settings" }
anyhow = { version = "1.0.71", features = ["backtrace"]}
reqwest = { version = "0.11", features = ["json"] }
sentry-tracing = {version = "0.31.0"}
sentry = { version = "0.31.0",features = ["backtrace", "anyhow"] }
sentry-anyhow = { version= "0.31.1", features = ["backtrace"]}
serde_json = "1.0.33"
serde = { version  = "1.0.159", features = ["derive"]}
serde_yaml = "0.9.27"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry-instrumentation-sdk = "0.12.0"
tar = "0.4.40"
flate2 = "1.0.28"
sha256 = "1.1.2"
zip = "0.6.6"
chrono = { version = "0.4.31", features = ["serde"] }
nix = {version="0.27.1", features=["user"]}